when:
  - event: pull_request
  - event: push
    branch: [ main, releases/* ]

steps:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 5
      lfs: false
      tags: true

  check:
    image: adoptopenjdk/openjdk11:alpine
    commands: ./gradlew --no-daemon clean check
