name: Gradle upload to binTray

on:
  release:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: eskatos/gradle-command-action@v1
      env:
        BINTRAY_USER: ${{ secrets.bintrayUsername }}
        BINTRAY_KEY: ${{ secrets.bintrayApiKey }}
      with:
        arguments: bintrayUpload
